-- Central composition manifest for the application-facing game systems.
-- Feature modules remain independently require-able; game.app constructs the
-- runtime-facing services after it has created authoritative application state.
return {
    adventureComposition = require("game.adventure_composition"),
    audioRuntime = require("game.audio_runtime"),
    assetStreamer = require("game.asset_streamer"),
    battleRuntime = require("game.battle_runtime"),
    battleUI = require("game.battle_ui"),
    contentRegistry = require("game.content_registry"),
    eventRuntime = require("game.event_runtime"),
    gameplayHUD = require("game.gameplay_hud"),
    gameplayInput = require("game.gameplay_input"),
    gameplayUpdate = require("game.gameplay_update"),
    inputComposition = require("game.input_composition"),
    interactions = require("game.interaction_router"),
    intro = require("game.intro_cinematic"),
    inventory = require("game.inventory_ui"),
    inventoryActions = require("game.inventory_actions"),
    inventoryPresenter = require("game.inventory_presenter"),
    journeyRules = require("game.journey_rules"),
    mobileRuntime = require("game.mobile_runtime"),
    platformComposition = require("game.platform_composition"),
    persistenceRuntime = require("game.persistence_runtime"),
    presentationRuntime = require("game.presentation_runtime"),
    screens = require("game.screen_manager"),
    screenFlow = require("game.screen_flow"),
    screenUI = require("game.screen_ui"),
    session = require("game.game_session"),
    sessionBootstrap = require("game.session_bootstrap"),
    startupRuntime = require("game.startup_runtime"),
    trainCarRuntime = require("game.train_car_runtime"),
    viewComposition = require("game.view_composition"),
    worldSessionComposition = require("game.world_session_composition"),
    worldScene = require("game.world_scene"),
    worldRenderer = require("game.world_renderer"),
}
