-- Central composition manifest for the application-facing game systems.
-- Feature modules remain independently require-able; application_composition
-- constructs runtime-facing services after creating authoritative state.
return {
    adventureComposition = require("game.adventure_composition"),
    audioRuntime = require("game.audio_runtime"),
    assetStreamer = require("game.asset_streamer"),
    battleRuntime = require("game.battle_runtime"),
    battleUI = require("game.battle_ui"),
    combatBalance = require("game.combat_balance"),
    contentRegistry = require("game.content_registry"),
    eventBalance = require("game.event_balance"),
    eventRuntime = require("game.event_runtime"),
    gameplayHUD = require("game.gameplay_hud"),
    gameplayInput = require("game.gameplay_input"),
    gameplayUpdate = require("game.gameplay_update"),
    inputComposition = require("game.input_composition"),
    interactions = require("game.interaction_router"),
    intro = require("game.intro_cinematic"),
    inventory = require("game.inventory_ui"),
    inventoryActions = require("game.inventory_actions"),
    inventoryPresenter = require("game.inventory_presenter"),
    journeyRules = require("game.journey_rules"),
    mobileRuntime = require("game.mobile_runtime"),
    platformComposition = require("game.platform_composition"),
    persistenceRuntime = require("game.persistence_runtime"),
    presentationRuntime = require("game.presentation_runtime"),
    progressionBalance = require("game.progression_balance"),
    screens = require("game.screen_manager"),
    screenFlow = require("game.screen_flow"),
    screenUI = require("game.screen_ui"),
    serviceRegistry = require("game.service_registry"),
    session = require("game.game_session"),
    sessionBootstrap = require("game.session_bootstrap"),
    smokeComposition = require("game.smoke_composition"),
    smokePlaythrough = require("game.smoke_playthrough"),
    startupRuntime = require("game.startup_runtime"),
    startupComposition = require("game.startup_composition"),
    trainCarRuntime = require("game.train_car_runtime"),
    trainUpgradeBalance = require("game.train_upgrade_balance"),
    viewComposition = require("game.view_composition"),
    worldSessionComposition = require("game.world_session_composition"),
    worldScene = require("game.world_scene"),
    worldRenderer = require("game.world_renderer"),
}
