-- Dedicated shooting-range test save. Install as saves/slot3.lua.
return {
  ["version"] = 30,
  ["character"] = "ferret-scout.png",
  ["location"] = 2,
  ["scene"] = "stop",
  ["stopped"] = true,
  ["playerX"] = 735,
  ["playerY"] = 565,
  ["health"] = 20,
  ["maxHealth"] = 20,
  ["resources"] = { ["food"] = 50, ["water"] = 50, ["coal"] = 50, ["oil"] = 50 },
  ["stats"] = { ["level"] = 1, ["xp"] = 0, ["nextXP"] = 10 },
  ["equipment"] = {
    [1] = "frontier-22-target-pistol",
    [2] = "frontier-22-lever-rifle",
  },
  ["inventory"] = {},
  ["inventoryCapacity"] = 12,
  ["ammo"] = {
    ["22lr"] = 500,
    ["rocks"] = 100,
    ["arrows"] = 100,
    ["ball-bearings"] = 100,
    ["9mm"] = 100,
    ["45-cal"] = 100,
    ["556"] = 100,
    ["30-carbine"] = 100,
    ["8mm"] = 100,
    ["380-acp"] = 100,
    ["32-acp"] = 100,
    ["12-gauge"] = 100,
    ["762x39"] = 100,
  },
  ["npcRoster"] = { [1] = "ferret-medic.png", [2] = "ferret-engineer.png" },
  ["currentNPC"] = "ferret-medic.png",
  ["visitedStops"] = { [1] = true, [2] = true },
  ["stopLayouts"] = {},
  ["npcStates"] = {},
  ["houseInitialized"] = {},
  ["houseLayoutsArranged"] = {},
  ["stopSludges"] = {},
  ["events"] = {},
  ["eventCategoryHistory"] = {},
  ["weaponDurability"] = {},
  ["weaponProficiency"] = {},
  ["supplyQuests"] = {},
  ["mailQuests"] = {},
  ["passengers"] = {},
  ["questAsked"] = {},
  ["lootRolls"] = {},
  ["nextBattlePotions"] = {},
  ["npcOffers"] = {},
  ["npcWeapons"] = {},
  ["encounters"] = {},
  ["choices"] = {},
  ["helpHistory"] = {},
  ["relationships"] = {},
  ["helpQuestSessions"] = {},
  ["droppedItems"] = {},
  ["trainCars"] = { [1] = "living-car" },
  ["activeCar"] = 1,
  ["engineLevel"] = 0,
  ["maintenance"] = { ["condition"] = 100, ["lastServicedStop"] = 0, ["totalServices"] = 0, ["totalWear"] = 0 },
  ["finale"] = {},
  ["scrap"] = 100,
  ["goodwill"] = 0,
  ["weaponDropsAdded"] = true,
  ["starterChestAdded"] = true,
  ["medicalDropsAdded"] = true,
  ["ammoDropsAdded"] = true,
  ["specialItemsAdded"] = true,
  ["lootContainerMigration"] = true,
  ["expandedLootAdded"] = true,
  ["radioAdded"] = true,
  ["lootBalanceVersion"] = 1,
  ["audio"] = {
    ["station"] = "8bit",
    ["musicVolume"] = 0.10,
    ["sfxVolume"] = 0.70,
    ["rainVolume"] = 0.20,
    ["rainEnabled"] = false,
    ["musicPaused"] = false,
    ["musicMuted"] = false,
  },
  ["accessibility"] = {
    ["version"] = 1,
    ["textSize"] = 1,
    ["highContrast"] = false,
    ["reducedMotion"] = false,
    ["controlHints"] = true,
    ["touchFeedback"] = true,
    ["largeTouchTargets"] = true,
  },
}
