from __future__ import annotations

import re
import struct
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


class LuaArchitectureTests(unittest.TestCase):
    def test_main_is_a_thin_lifecycle_shell(self) -> None:
        source = (ROOT / "main.lua").read_text(encoding="utf-8")
        active_lines = [line for line in source.splitlines() if line.strip() and not line.lstrip().startswith("--")]
        self.assertLessEqual(len(active_lines), 24)
        self.assertIn('require("game.app")', source)
        self.assertEqual(re.findall(r'require\("game\.[^"]+"\)', source), ['require("game.app")'])

        expected_callbacks = {
            "load", "update", "draw", "mousepressed", "mousemoved", "mousereleased",
            "wheelmoved", "keypressed", "keyreleased", "touchpressed", "touchmoved",
            "touchreleased", "focus", "quit",
        }
        forwarded = set(re.findall(r"function love\.([a-z]+)\(", source))
        self.assertEqual(forwarded, expected_callbacks)

    def test_application_boundaries_exist(self) -> None:
        app_adapter = (ROOT / "game" / "app.lua").read_text(encoding="utf-8")
        application_composition = (ROOT / "game" / "application_composition.lua").read_text(encoding="utf-8")
        app = app_adapter + "\n" + application_composition
        systems = (ROOT / "game" / "systems.lua").read_text(encoding="utf-8")
        schema = (ROOT / "game" / "save_schema.lua").read_text(encoding="utf-8")
        save = (ROOT / "game" / "save.lua").read_text(encoding="utf-8")
        config = (ROOT / "game" / "config.lua").read_text(encoding="utf-8")
        runtime = (ROOT / "game" / "runtime_state.lua").read_text(encoding="utf-8")
        bootstrap = (ROOT / "game" / "session_bootstrap.lua").read_text(encoding="utf-8")
        gameplay_input = (ROOT / "game" / "gameplay_input.lua").read_text(encoding="utf-8")
        gameplay_update = (ROOT / "game" / "gameplay_update.lua").read_text(encoding="utf-8")
        inventory_actions = (ROOT / "game" / "inventory_actions.lua").read_text(encoding="utf-8")
        inventory = (ROOT / "game" / "inventory.lua").read_text(encoding="utf-8")
        journey_rules = (ROOT / "game" / "journey_rules.lua").read_text(encoding="utf-8")
        screen_ui = (ROOT / "game" / "screen_ui.lua").read_text(encoding="utf-8")
        world_renderer = (ROOT / "game" / "world_renderer.lua").read_text(encoding="utf-8")
        assets = (ROOT / "game" / "assets.lua").read_text(encoding="utf-8")
        stop_sludges = (ROOT / "game" / "stop_sludges.lua").read_text(encoding="utf-8")
        gameplay_hud = (ROOT / "game" / "gameplay_hud.lua").read_text(encoding="utf-8")
        battle_runtime = (ROOT / "game" / "battle_runtime.lua").read_text(encoding="utf-8")
        battle_rules = (ROOT / "game" / "battle_rules.lua").read_text(encoding="utf-8")
        battle_controller = (ROOT / "game" / "battle_controller.lua").read_text(encoding="utf-8")
        battle_ui = (ROOT / "game" / "battle_ui.lua").read_text(encoding="utf-8")
        weapon_attachment = (ROOT / "game" / "weapon_attachment.lua").read_text(encoding="utf-8")
        weapon_attachment_points = (ROOT / "game" / "weapon_attachment_points.lua").read_text(encoding="utf-8")
        battle_grid = (ROOT / "game" / "battle_grid.lua").read_text(encoding="utf-8")
        world_scene = (ROOT / "game" / "world_scene.lua").read_text(encoding="utf-8")
        audio_runtime = (ROOT / "game" / "audio_runtime.lua").read_text(encoding="utf-8")
        inventory_presenter = (ROOT / "game" / "inventory_presenter.lua").read_text(encoding="utf-8")
        event_runtime = (ROOT / "game" / "event_runtime.lua").read_text(encoding="utf-8")
        train_car_runtime = (ROOT / "game" / "train_car_runtime.lua").read_text(encoding="utf-8")
        mobile_runtime = (ROOT / "game" / "mobile_runtime.lua").read_text(encoding="utf-8")
        mobile_controls = (ROOT / "game" / "mobile_controls.lua").read_text(encoding="utf-8")
        presentation_runtime = (ROOT / "game" / "presentation_runtime.lua").read_text(encoding="utf-8")
        startup_runtime = (ROOT / "game" / "startup_runtime.lua").read_text(encoding="utf-8")
        persistence_runtime = (ROOT / "game" / "persistence_runtime.lua").read_text(encoding="utf-8")
        smoke_playthrough = (ROOT / "game" / "smoke_playthrough.lua").read_text(encoding="utf-8")
        screen_flow = (ROOT / "game" / "screen_flow.lua").read_text(encoding="utf-8")
        content_registry = (ROOT / "game" / "content_registry.lua").read_text(encoding="utf-8")
        view_composition = (ROOT / "game" / "view_composition.lua").read_text(encoding="utf-8")
        adventure_composition = (ROOT / "game" / "adventure_composition.lua").read_text(encoding="utf-8")
        platform_composition = (ROOT / "game" / "platform_composition.lua").read_text(encoding="utf-8")
        input_composition = (ROOT / "game" / "input_composition.lua").read_text(encoding="utf-8")
        world_session_composition = (ROOT / "game" / "world_session_composition.lua").read_text(encoding="utf-8")
        startup_composition = (ROOT / "game" / "startup_composition.lua").read_text(encoding="utf-8")
        service_registry = (ROOT / "game" / "service_registry.lua").read_text(encoding="utf-8")
        smoke_composition = (ROOT / "game" / "smoke_composition.lua").read_text(encoding="utf-8")
        progression_balance = (ROOT / "game" / "progression_balance.lua").read_text(encoding="utf-8")
        combat_balance = (ROOT / "game" / "combat_balance.lua").read_text(encoding="utf-8")
        event_balance = (ROOT / "game" / "event_balance.lua").read_text(encoding="utf-8")
        train_upgrade_balance = (ROOT / "game" / "train_upgrade_balance.lua").read_text(encoding="utf-8")
        train = (ROOT / "game" / "train.lua").read_text(encoding="utf-8")
        maintenance = (ROOT / "game" / "maintenance.lua").read_text(encoding="utf-8")
        engine_upgrades = (ROOT / "game" / "engine_upgrades.lua").read_text(encoding="utf-8")
        loot_progression = (ROOT / "game" / "loot_progression.lua").read_text(encoding="utf-8")
        quest_progression = (ROOT / "game" / "quest_progression.lua").read_text(encoding="utf-8")
        player_progression = (ROOT / "game" / "player_progression.lua").read_text(encoding="utf-8")
        stop_help_progression = (ROOT / "game" / "stop_help_progression.lua").read_text(encoding="utf-8")
        npc_relationships = (ROOT / "game" / "npc_relationships.lua").read_text(encoding="utf-8")
        accessibility = (ROOT / "game" / "accessibility.lua").read_text(encoding="utf-8")
        stop_activities = (ROOT / "game" / "stop_activities.lua").read_text(encoding="utf-8")
        wildlife = (ROOT / "game" / "wildlife.lua").read_text(encoding="utf-8")
        mice = (ROOT / "game" / "mice.lua").read_text(encoding="utf-8")
        first_aid = (ROOT / "game" / "first_aid.lua").read_text(encoding="utf-8")
        help_quest_session = (ROOT / "game" / "help_quest_session.lua").read_text(encoding="utf-8")
        help_dialogue_quests = (ROOT / "game" / "help_dialogue_quests.lua").read_text(encoding="utf-8")
        sludge_containment = (ROOT / "game" / "sludge_containment.lua").read_text(encoding="utf-8")
        track_debris_clearing = (ROOT / "game" / "track_debris_clearing.lua").read_text(encoding="utf-8")
        stop_activity_minigames = (ROOT / "game" / "stop_activity_minigames.lua").read_text(encoding="utf-8")
        activity_minigame_ui = (ROOT / "game" / "activity_minigame_ui.lua").read_text(encoding="utf-8")
        activity_difficulty = (ROOT / "game" / "activity_difficulty.lua").read_text(encoding="utf-8")
        garden_rescue = (ROOT / "game" / "garden_rescue.lua").read_text(encoding="utf-8")
        wildlife_trough_care = (ROOT / "game" / "wildlife_trough_care.lua").read_text(encoding="utf-8")
        finale_progression = (ROOT / "game" / "finale_progression.lua").read_text(encoding="utf-8")
        passengers = (ROOT / "game" / "passengers.lua").read_text(encoding="utf-8")
        stops = (ROOT / "game" / "stops.lua").read_text(encoding="utf-8")
        interaction_router = (ROOT / "game" / "interaction_router.lua").read_text(encoding="utf-8")
        events = (ROOT / "game" / "events.lua").read_text(encoding="utf-8")
        catalog = (ROOT / "game" / "catalog.lua").read_text(encoding="utf-8")

        for callback in ("load", "update", "draw", "keypressed", "mousepressed", "quit"):
            self.assertIn(f"function App.{callback}", app)
        self.assertTrue(app_adapter.rstrip().endswith("return App"))
        active_app_lines = [line for line in app_adapter.splitlines() if line.strip() and not line.lstrip().startswith("--")]
        self.assertLessEqual(len(active_app_lines), 26)
        self.assertEqual(re.findall(r'require\("game\.[^"]+"\)', app_adapter), ['require("game.application_composition")'])
        self.assertIn('require("game.application_composition").new({engine=love})', app_adapter)
        self.assertNotIn('require("game.systems")', app_adapter)
        self.assertIn('require("game.systems")', app)
        self.assertIn('require("game.save_schema")', app)
        self.assertIn('require("game.config")', app)
        self.assertIn('require("game.runtime_state")', app)
        self.assertNotRegex(app, r"local\s+state\s*=")
        self.assertNotRegex(app, r"local\s+selectedSlot\s*[,=]")
        self.assertNotRegex(app, r"local\s+scene\s*[,=]")
        self.assertIn("CURRENT_VERSION = 30", schema)
        self.assertIn("function SaveSchema.migrate", schema)
        self.assertIn("function SaveSchema.validate", schema)
        self.assertIn("SaveSchema.migrations=migrations", schema)
        self.assertIn("rewriteRequired=steps>0 or not wasCanonical", schema)
        self.assertIn('require("game.save_schema")', save)
        self.assertIn("SaveSchema.migrate(data)", save)
        self.assertIn("SaveSchema.migrate(data)", bootstrap)
        self.assertIn("baseWidth = 960", config)
        self.assertIn("game.gameplay_input", systems)
        self.assertIn("function RuntimeState:syncForSave", runtime)
        self.assertIn("function RuntimeState:isSynchronized", runtime)
        self.assertIn("return {new=new}", bootstrap)
        self.assertNotIn("setfenv", bootstrap)
        self.assertNotIn("dependency resolver", bootstrap)
        self.assertIn("local sessionBootstrap=SessionBootstrap.new({", world_session_composition)
        self.assertIn("return {new=new}", gameplay_input)
        self.assertNotIn("setfenv", gameplay_input)
        self.assertNotIn("dependency resolver", gameplay_input)
        self.assertIn("local gameplayInput=GameplayInput.new({", input_composition)
        self.assertNotIn('required(context,"systems"', gameplay_input)
        self.assertNotIn("Systems.", gameplay_input)
        self.assertIn("return {new=new}", gameplay_update)
        self.assertNotIn("setfenv", gameplay_update)
        self.assertNotIn("dependency resolver", gameplay_update)
        self.assertIn("gameplayUpdate=Modules.gameplayUpdate", app)
        self.assertNotIn("resolveGameplayUpdate", app)
        self.assertIn("return {new=new}", inventory_actions)
        self.assertNotIn("setfenv", inventory_actions)
        self.assertNotIn("dependency resolver", inventory_actions)
        self.assertIn("inventoryActions=InventoryActions.new({", adventure_composition)
        self.assertNotIn("resolveInventoryActions", app)
        self.assertIn("return {new=new}", journey_rules)
        self.assertNotIn("setfenv", journey_rules)
        self.assertNotIn("dependency resolver", journey_rules)
        self.assertIn("journeyRules=JourneyRules.new({", adventure_composition)
        self.assertIn('local ProgressionBalance=required(context,"progressionBalance","table")', journey_rules)
        self.assertIn("progressionBalance=ProgressionBalance", adventure_composition)
        self.assertIn("progressionBalance=Modules.progressionBalance", application_composition)
        self.assertIn('progressionBalance = require("game.progression_balance")', systems)
        self.assertIn("return Balance", progression_balance)
        self.assertIn("function Balance.travelCost", progression_balance)
        self.assertIn("function Balance.travelStatus", progression_balance)
        self.assertIn("function Balance.audit", progression_balance)
        self.assertIn("travelStatus=travelStatus", journey_rules)
        self.assertIn("balanceAudit=function() return ProgressionBalance.audit(EngineUpgrades,TrainUpgradeBalance) end", journey_rules)
        self.assertNotIn("resolveJourneyRules", app)
        self.assertIn("return {new=new}", screen_ui)
        self.assertNotIn("setfenv", screen_ui)
        self.assertNotIn("dependency resolver", screen_ui)
        self.assertIn("screenUI=ScreenUI.new({", view_composition)
        self.assertNotIn("resolveScreenUI", app)
        self.assertIn("return {new=new}", world_renderer)
        self.assertNotIn("setfenv", world_renderer)
        self.assertNotIn("dependency resolver", world_renderer)
        self.assertIn("worldRenderer=WorldRenderer.new({", view_composition)
        self.assertNotIn("resolveWorldRenderer", app)
        self.assertIn("return {new=new}", gameplay_hud)
        self.assertNotIn("setfenv", gameplay_hud)
        self.assertNotIn("dependency resolver", gameplay_hud)
        self.assertIn("gameplayHUD=GameplayHUD.new({", view_composition)
        self.assertNotIn("resolveGameplayHUD", app)
        self.assertIn('battleRuntime = require("game.battle_runtime")', systems)
        self.assertIn("return {new=new}", battle_runtime)
        self.assertNotIn("setfenv", battle_runtime)
        self.assertNotIn("dependency resolver", battle_runtime)
        self.assertIn("battleRuntime=BattleRuntime.new({", adventure_composition)
        self.assertNotIn("local function battleContext", app)
        self.assertNotIn("function ui.battleUIContext", app)
        self.assertIn("useBattleHealingItem=battleRuntime.useHealingItem", adventure_composition)
        self.assertIn('combatBalance = require("game.combat_balance")', systems)
        self.assertIn("combatBalance=Modules.combatBalance", application_composition)
        self.assertIn('local CombatBalance=required(context,"combatBalance","table")', adventure_composition)
        self.assertIn("combatBalance=CombatBalance", adventure_composition)
        self.assertIn("return Balance", combat_balance)
        self.assertIn("function Balance.tierFor", combat_balance)
        self.assertIn("function Balance.enemyProfile", combat_balance)
        self.assertIn("function Balance.mobCount", combat_balance)
        self.assertIn("function Balance.rewardProfile", combat_balance)
        self.assertIn("function Balance.audit", combat_balance)
        self.assertIn('local CombatBalance=required(context,"combatBalance","table")', battle_runtime)
        self.assertIn("CombatBalance=CombatBalance", battle_runtime)
        self.assertIn("balanceAudit=balanceAudit", battle_runtime)
        self.assertIn("CombatBalance.tierFor", journey_rules)
        self.assertIn("CombatBalance.mobCount", journey_rules)
        self.assertIn("Events.resolve(runtime.saveData,Catalog,event,index,CombatBalance,TrainUpgradeBalance)", event_runtime)
        self.assertIn("function Events.resolve(data,catalog,event,choiceIndex,CombatBalance,TrainUpgradeBalance)", events)
        self.assertNotIn("function Catalog.encounterMobCount", catalog)
        self.assertIn("c.CombatBalance.enemyProfile", battle_controller)
        self.assertIn("c.CombatBalance.rewardProfile", battle_controller)
        self.assertNotIn("c.saveData.location<=4", battle_controller)
        self.assertIn('local combatBalanceAudit=required(context,"combatBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="combat_balance_curve"', smoke_playthrough)
        self.assertIn('playerProgression = require("game.player_progression")', systems)
        self.assertIn("playerProgression=Modules.playerProgression", application_composition)
        self.assertIn('local PlayerProgression=required(context,"playerProgression","table")', world_session_composition)
        self.assertIn("playerProgression=PlayerProgression", world_session_composition)
        self.assertIn("stats=PlayerProgression.newStats()", bootstrap)
        self.assertIn("PlayerProgression.ensure(data)", bootstrap)
        self.assertNotIn("stats={level=1,xp=0,nextXP=10}", bootstrap)
        self.assertIn("return Progression", player_progression)
        self.assertIn("Progression.maxLevel=12", player_progression)
        self.assertIn("function Progression.requirement", player_progression)
        self.assertIn("function Progression.gainExperience", player_progression)
        self.assertIn("function Progression.combatBonuses", player_progression)
        self.assertIn("function Progression.abilityProfile", player_progression)
        self.assertIn("function Progression.audit", player_progression)
        self.assertIn('require("game.player_progression")', battle_rules)
        self.assertIn("return PlayerProgression.gainExperience(data,amount)", battle_rules)
        self.assertNotIn("stats.nextXP * 1.45", battle_rules)
        self.assertIn("c.PlayerProgression.combatBonuses", battle_controller)
        self.assertIn("c.PlayerProgression.abilityProfile", battle_controller)
        self.assertNotIn("math.floor((d.stats.level-1)/2)", battle_controller)
        self.assertNotIn("a.hp+4", battle_controller)
        self.assertNotIn("closest.sleepRounds=2", battle_controller)
        self.assertNotIn("closest.hp-5", battle_controller)
        self.assertIn('local PlayerProgression=required(context,"playerProgression","table")', battle_runtime)
        self.assertIn("playerBalanceAudit=playerBalanceAudit", battle_runtime)
        self.assertIn("ctx.playerProgression.abilityProfile", battle_ui)
        self.assertIn('button("ABILITY R"', battle_ui)
        self.assertIn("PlayerProgression.status(runtime.saveData)", screen_ui)
        self.assertIn('local playerBalanceAudit=required(context,"playerBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="player_progression_curve"', smoke_playthrough)
        self.assertIn('stopHelpProgression = require("game.stop_help_progression")', systems)
        self.assertIn('firstAid = require("game.first_aid")', systems)
        self.assertIn("stopHelpProgression=Modules.stopHelpProgression", application_composition)
        self.assertIn("firstAid=Modules.firstAid", application_composition)
        self.assertIn('local StopHelpProgression=required(context,"stopHelpProgression","table")', world_session_composition)
        self.assertIn("StopHelpProgression.ensure(data)", bootstrap)
        self.assertIn("goodwill=0, helpHistory={}", bootstrap)
        self.assertIn("relationships={}", bootstrap)
        self.assertIn('"maintenance", "eventCategoryHistory", "helpHistory"', schema)
        self.assertIn('"relationships"', schema)
        self.assertIn('"accessibility"', schema)
        self.assertIn('accessibility={version=1', bootstrap)
        self.assertIn('"scrap","goodwill"', schema)
        self.assertIn("function StopHelp.ensure", stop_help_progression)
        self.assertIn("function StopHelp.completeItem", stop_help_progression)
        self.assertIn("function StopHelp.completeAid", stop_help_progression)
        self.assertIn("function StopHelp.add", stop_help_progression)
        self.assertIn('require("game.help_quest_session")', stop_help_progression)
        self.assertIn("Relationships.recordHelp(data,npc,gained,kind,location)", stop_help_progression)
        self.assertIn("math.max(0", stop_help_progression)
        self.assertIn("noNegativeAlignment=noEvil", stop_help_progression)
        self.assertIn('npcRelationships = require("game.npc_relationships")', systems)
        self.assertIn("npcRelationships=Modules.npcRelationships", application_composition)
        self.assertIn("function Relationships.ensureData", npc_relationships)
        self.assertIn("function Relationships.status", npc_relationships)
        self.assertIn("function Relationships.recordHelp", npc_relationships)
        self.assertIn("function Relationships.recordGift", npc_relationships)
        self.assertIn("function Relationships.merchantTerms", npc_relationships)
        self.assertIn("function Relationships.npcDialogue", npc_relationships)
        self.assertIn("function Relationships.passengerDialogue", npc_relationships)
        self.assertIn("function Relationships.audit", npc_relationships)
        self.assertIn("NpcRelationships.recordGift", gameplay_input)
        self.assertIn("NpcRelationships.buyPrice", gameplay_input)
        self.assertIn("NpcRelationships.sellPrice", gameplay_input)
        self.assertIn("NpcRelationships.passengerDialogue", gameplay_input)
        self.assertIn("NpcRelationships.npcDialogue", journey_rules)
        self.assertIn("NpcRelationships.merchantTerms", screen_ui)
        self.assertIn("function Catalog.characterIdentity", catalog)
        self.assertIn("function Catalog.characterIdentityAudit", catalog)
        self.assertIn('love.graphics.printf("TRAVELER PROFILE"', screen_ui)
        self.assertIn('button("CHOOSE THIS TRAVELER"', screen_ui)
        self.assertIn("chooseCharacter(runtime.characterPreviewFile)", gameplay_input)
        self.assertIn('name="npc_relationship_progression"', smoke_playthrough)
        self.assertIn('name="character_identity_roster"', smoke_playthrough)
        self.assertIn('name="persistent_gift_response"', smoke_playthrough)
        self.assertIn('accessibility = require("game.accessibility")', systems)
        self.assertIn("function Accessibility.ensure", accessibility)
        self.assertIn("function Accessibility.textScale", accessibility)
        self.assertIn("function Accessibility.cycleTextSize", accessibility)
        self.assertIn("function Accessibility.motionSpeed", accessibility)
        self.assertIn("function Accessibility.touchProfile", accessibility)
        self.assertIn("function Accessibility.audit", accessibility)
        self.assertIn('runtime.optionsPage="accessibility"', gameplay_input)
        self.assertIn('Accessibility.toggle(runtime.saveData,"highContrast")', gameplay_input)
        self.assertIn('Accessibility.enabled(runtime.saveData,"controlHints")', gameplay_hud)
        self.assertIn('Accessibility.enabled(saveData,"highContrast")', battle_ui)
        self.assertIn('Accessibility.motionSpeed(runtime.saveData)', gameplay_update)
        self.assertIn('Accessibility.motionSpeed(runtime.saveData)', battle_runtime)
        self.assertIn("self:_feedback(gx,gy)", mobile_controls)
        self.assertIn('name="accessibility_preferences"', smoke_playthrough)
        self.assertIn('name="accessibility_settings_controls"', smoke_playthrough)
        self.assertIn("function FirstAid.choose", first_aid)
        self.assertIn("function FirstAid.mousepressed", first_aid)
        self.assertIn("function FirstAid.keypressed", first_aid)
        self.assertIn("function FirstAid.audit", first_aid)
        self.assertIn('QuestProgression.offerOrder={"mail","ride","supplies","trade","item","aid","dialogue","none"}', quest_progression)
        self.assertIn("early.none>=.5999", quest_progression)
        self.assertIn("layout.offerPolicyVersion=StopHelpProgression.policyVersion", stops)
        self.assertIn("StopHelpProgression.ensureRequest", stops)
        self.assertIn('local StopHelpProgression=required(context,"stopHelpProgression","table")', adventure_composition)
        self.assertIn('local HelpQuestSession=required(context,"helpQuestSession","table")', adventure_composition)
        self.assertIn('local FirstAid=required(context,"firstAid","table")', adventure_composition)
        self.assertIn("resolveFirstAid=resolveFirstAid", journey_rules)
        self.assertIn("helpBalanceAudit=function()", journey_rules)
        self.assertIn("FirstAid.draw(runtime.firstAid,colors)", gameplay_hud)
        self.assertIn('button("EXIT HOME",700,150,238,66,true,.92)', gameplay_hud)
        self.assertIn('button("EXIT HOME",790,194,135,38,true,.78)', gameplay_hud)
        self.assertIn('runtime.scene=="house" and ui.exitHome and Util.pointIn(x,y,ui.exitHome)', gameplay_input)
        self.assertIn('local function exitHouse()', gameplay_input)
        self.assertIn('name="exit_home_button"', smoke_playthrough)
        self.assertIn('name="mobile_exit_home_touch"', smoke_playthrough)
        self.assertIn('local FirstAid=required(context,"firstAid","table")', gameplay_input)
        self.assertIn("FirstAid.mousepressed(runtime.firstAid", gameplay_input)
        self.assertIn("FirstAid.keypressed(runtime.firstAid", gameplay_input)
        self.assertIn("not runtime.firstAid", presentation_runtime)
        self.assertIn("not runtime.firstAid", mobile_runtime)
        self.assertIn('local helpBalanceAudit=required(context,"helpBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="stop_help_goodwill"', smoke_playthrough)
        self.assertIn('helpQuestSession = require("game.help_quest_session")', systems)
        self.assertIn("function HelpQuest.ensureData", help_quest_session)
        self.assertIn("function HelpQuest.ensure", help_quest_session)
        self.assertIn("function HelpQuest.accept", help_quest_session)
        self.assertIn("function HelpQuest.investigate", help_quest_session)
        self.assertIn("function HelpQuest.activate", help_quest_session)
        self.assertIn("function HelpQuest.pause", help_quest_session)
        self.assertIn("function HelpQuest.resume", help_quest_session)
        self.assertIn("function HelpQuest.resolve", help_quest_session)
        self.assertIn("function HelpQuest.importResolved", help_quest_session)
        self.assertIn("function HelpQuest.claim", help_quest_session)
        self.assertIn("function HelpQuest.summary", help_quest_session)
        self.assertIn('name="help_quest_session_lifecycle"', smoke_playthrough)
        self.assertIn('helpDialogueQuests = require("game.help_dialogue_quests")', systems)
        self.assertIn('DialogueQuests.order={"missing-family","crop-dispute","bandit-warning","broken-promise"}', help_dialogue_quests)
        self.assertIn("function DialogueQuests.ensure", help_dialogue_quests)
        self.assertIn("function DialogueQuests.begin", help_dialogue_quests)
        self.assertIn("function DialogueQuests.choose", help_dialogue_quests)
        self.assertIn("function DialogueQuests.pause", help_dialogue_quests)
        self.assertIn("function DialogueQuests.followup", help_dialogue_quests)
        self.assertIn("HelpQuest.claim(data,session.id,award)", help_dialogue_quests)
        self.assertIn('name="branching_help_dialogue_quests"', smoke_playthrough)
        self.assertIn("runtime.helpDialogue", screen_ui)
        self.assertIn("ui.helpDialogueChoices", screen_ui)
        self.assertIn("chooseHelpDialogue(index)", gameplay_input)
        self.assertIn("chooseHelpDialogue(nil)", gameplay_input)
        self.assertIn('local chooseHelpDialogue=required(context,"chooseHelpDialogue","function")', input_composition)
        self.assertIn('stopActivities = require("game.stop_activities")', systems)
        self.assertIn("stopActivities=Modules.stopActivities", application_composition)
        self.assertIn("function Activities.kindFor", stop_activities)
        self.assertIn("function Activities.complete", stop_activities)
        self.assertIn("function Activities.update", stop_activities)
        self.assertIn("function Activities.audit", stop_activities)
        self.assertIn("StopActivities.ensure", world_scene)
        self.assertIn("StopActivities.update", world_scene)
        self.assertIn("StopActivities.complete", world_scene)
        self.assertIn("drawStopActivity()", world_renderer)
        self.assertIn('kind="stopActivity"', interaction_router)
        self.assertIn("runtime.stopHazardSlow", gameplay_update)
        self.assertIn('elseif action=="stopActivity" then completeStopActivity()', gameplay_input)
        self.assertIn('elseif kind=="stopActivity" then return "q","HELP"', mobile_runtime)
        self.assertIn("ecology.player", wildlife)
        self.assertIn("ecology.feed", wildlife)
        self.assertIn("ecology.player", mice)
        self.assertIn("ecology.feed", mice)
        self.assertIn('name="stop_world_variety"', smoke_playthrough)
        self.assertIn('name="settlement_activity_help"', smoke_playthrough)
        self.assertIn('name="mobile_settlement_help_touch"', smoke_playthrough)
        self.assertIn('sludgeContainment = require("game.sludge_containment")', systems)
        self.assertIn('trackDebrisClearing = require("game.track_debris_clearing")', systems)
        self.assertIn('stopActivityMinigames = require("game.stop_activity_minigames")', systems)
        self.assertIn('activityMinigameUI = require("game.activity_minigame_ui")', systems)
        self.assertIn('gardenRescue = require("game.garden_rescue")', systems)
        self.assertIn('wildlifeTroughCare = require("game.wildlife_trough_care")', systems)
        self.assertIn("function SludgeContainment.new", sludge_containment)
        self.assertIn("function SludgeContainment.choose", sludge_containment)
        self.assertIn("function SludgeContainment.mousepressed", sludge_containment)
        self.assertIn("function SludgeContainment.keypressed", sludge_containment)
        self.assertIn("function SludgeContainment.draw", sludge_containment)
        self.assertIn("function SludgeContainment.audit", sludge_containment)
        self.assertIn('["sludge-seep"]="sludge-containment"', stop_activities)
        self.assertIn('["track-debris"]="track-debris-clearing"', stop_activities)
        self.assertIn("function TrackDebris.new", track_debris_clearing)
        self.assertIn("function TrackDebris.choose", track_debris_clearing)
        self.assertIn("function TrackDebris.mousepressed", track_debris_clearing)
        self.assertIn("function TrackDebris.keypressed", track_debris_clearing)
        self.assertIn("function TrackDebris.draw", track_debris_clearing)
        self.assertIn("function TrackDebris.audit", track_debris_clearing)
        self.assertIn("function Coordinator.new", stop_activity_minigames)
        self.assertIn('["sludge-containment"]', stop_activity_minigames)
        self.assertIn('["track-debris-clearing"]', stop_activity_minigames)
        self.assertIn('["garden-rescue"]', stop_activity_minigames)
        self.assertIn('["wildlife-trough-care"]', stop_activity_minigames)
        self.assertIn("function UI.hit", activity_minigame_ui)
        self.assertIn("function UI.sprite", activity_minigame_ui)
        self.assertIn("love.graphics.setColor(1,1,1,1)", activity_minigame_ui)
        self.assertIn("function UI.begin", activity_minigame_ui)
        self.assertIn("function UI.footer", activity_minigame_ui)
        self.assertIn("function Difficulty.profile", activity_difficulty)
        self.assertIn("function Difficulty.apply", activity_difficulty)
        self.assertIn("function Difficulty.goodwill", activity_difficulty)
        self.assertIn("function Difficulty.audit", activity_difficulty)
        self.assertIn('activityDifficulty = require("game.activity_difficulty")', systems)
        self.assertIn("activityDifficulty=Modules.activityDifficulty", application_composition)
        self.assertIn("function Garden.new", garden_rescue)
        self.assertIn("function Garden.choose", garden_rescue)
        self.assertIn("function Garden.draw", garden_rescue)
        self.assertIn("UI.sprite(image,3", garden_rescue)
        self.assertIn("function Garden.audit", garden_rescue)
        self.assertIn("function Wildlife.new", wildlife_trough_care)
        self.assertIn("function Wildlife.choose", wildlife_trough_care)
        self.assertIn("function Wildlife.draw", wildlife_trough_care)
        self.assertIn("UI.sprite(image,4", wildlife_trough_care)
        self.assertIn("function Wildlife.audit", wildlife_trough_care)
        self.assertIn("runtime.activityMinigame", gameplay_input)
        self.assertIn("ActivityMinigames.draw(runtime.activityMinigame", gameplay_hud)
        self.assertIn('runtime.activityMinigame and "activity-minigame"', presentation_runtime)
        self.assertIn('sludgeContainmentAtlas=loadImage("assets/sprites/props/sludge-containment-tools-atlas.png")', assets)
        self.assertTrue((ROOT / "assets" / "sprites" / "props" / "sludge-containment-tools-atlas.png").is_file())
        self.assertIn('trackDebrisAtlas=loadImage("assets/sprites/props/track-debris-tools-atlas.png")', assets)
        self.assertTrue((ROOT / "assets" / "sprites" / "props" / "track-debris-tools-atlas.png").is_file())
        self.assertIn('gardenRescueAtlas=loadImage("assets/sprites/props/garden-rescue-tools-atlas.png")', assets)
        self.assertIn('wildlifeTroughAtlas=loadImage("assets/sprites/props/wildlife-trough-tools-atlas.png")', assets)
        self.assertTrue((ROOT / "assets" / "sprites" / "props" / "garden-rescue-tools-atlas.png").is_file())
        self.assertTrue((ROOT / "assets" / "sprites" / "props" / "wildlife-trough-tools-atlas.png").is_file())
        self.assertIn('result.minigames.difficulty.curve=="activity-difficulty-v2"', smoke_playthrough)
        self.assertIn('result.curve=="stop-world-variety-v3"', smoke_playthrough)
        self.assertIn('result.minigames.sludge.curve=="sludge-containment-v2"', smoke_playthrough)
        self.assertIn('result.minigames.track.curve=="track-debris-v2"', smoke_playthrough)
        self.assertIn('result.minigames.garden.curve=="garden-rescue-v2"', smoke_playthrough)
        self.assertIn('result.minigames.wildlife.curve=="wildlife-trough-v2"', smoke_playthrough)
        self.assertIn('eventBalance = require("game.event_balance")', systems)
        self.assertIn("eventBalance=Modules.eventBalance", application_composition)
        self.assertIn('local EventBalance=required(context,"eventBalance","table")', adventure_composition)
        self.assertIn("eventBalance=EventBalance", adventure_composition)
        self.assertIn("return Balance", event_balance)
        self.assertIn("function Balance.encounterChance", event_balance)
        self.assertIn("function Balance.pickCategory", event_balance)
        self.assertIn("function Balance.alwaysAvailable", event_balance)
        self.assertIn("function Balance.audit", event_balance)
        self.assertIn("EventBalance.encounterChance", journey_rules)
        self.assertNotIn("love.math.random()<.58", journey_rules)
        self.assertIn('local EventBalance=required(context,"eventBalance","table")', event_runtime)
        self.assertIn("Events.random(runtime.saveData,EventBalance)", event_runtime)
        self.assertIn("balanceAudit=balanceAudit", event_runtime)
        self.assertIn("function Events.random(data,EventBalance)", events)
        self.assertIn("EventBalance.pickCategory", events)
        self.assertIn("data.eventCategoryHistory", events)
        self.assertIn("if choice and choice.fallback then return true end", events)
        self.assertIn('"maintenance", "eventCategoryHistory"', schema)
        self.assertIn("eventCategoryHistory={}", bootstrap)
        self.assertIn('local eventBalanceAudit=required(context,"eventBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="event_balance_curve"', smoke_playthrough)
        self.assertIn('trainUpgradeBalance = require("game.train_upgrade_balance")', systems)
        self.assertIn("trainUpgradeBalance=Modules.trainUpgradeBalance", application_composition)
        self.assertIn("Catalog.trainCarCatalog = TrainUpgradeBalance.carCatalog", catalog)
        self.assertIn("return Balance", train_upgrade_balance)
        self.assertIn("function Balance.resourceCapacity", train_upgrade_balance)
        self.assertIn("function Balance.addResource", train_upgrade_balance)
        self.assertIn("function Balance.applyArrival", train_upgrade_balance)
        self.assertIn("function Balance.purchaseCar", train_upgrade_balance)
        self.assertIn("function Balance.purchaseEngine", train_upgrade_balance)
        self.assertIn("function Balance.audit", train_upgrade_balance)
        self.assertIn('local TrainUpgradeBalance=required(context,"trainUpgradeBalance","table")', adventure_composition)
        self.assertIn("trainUpgradeBalance=TrainUpgradeBalance", adventure_composition)
        self.assertIn("TrainUpgradeBalance.applyArrival", gameplay_update)
        self.assertIn("TrainUpgradeBalance.purchaseEngine", gameplay_input)
        self.assertIn("TrainUpgradeBalance.purchaseCar", gameplay_input)
        self.assertIn("TrainUpgradeBalance.resourceCapacity", gameplay_hud)
        self.assertIn("TrainUpgradeBalance.carStatus", screen_ui)
        self.assertIn("TrainUpgradeBalance.engineStatus", screen_ui)
        self.assertIn("TrainUpgradeBalance.addResource", battle_controller)
        self.assertIn("TrainUpgradeBalance.addResource", journey_rules)
        self.assertNotRegex(journey_rules, r"math\.min\((20|30),runtime\.saveData\.resources")
        self.assertIn('local upgradeBalanceAudit=required(context,"upgradeBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="train_upgrade_balance"', smoke_playthrough)
        self.assertIn('lootProgression = require("game.loot_progression")', systems)
        self.assertIn("lootProgression=Modules.lootProgression", application_composition)
        self.assertIn('local LootProgression=required(context,"lootProgression","table")', adventure_composition)
        self.assertIn("lootProgression=LootProgression", adventure_composition)
        self.assertIn("function LootProgression.itemPrice", loot_progression)
        self.assertIn("function LootProgression.weaponCondition", loot_progression)
        self.assertIn("function LootProgression.wearWeapon", loot_progression)
        self.assertIn("function LootProgression.repairEquipped", loot_progression)
        self.assertIn("function LootProgression.resalePrice", loot_progression)
        self.assertIn("function LootProgression.validate", loot_progression)
        self.assertIn("function LootProgression.audit", loot_progression)
        self.assertIn("ammunition unlocks after weapon", loot_progression)
        self.assertIn("LootProgression.itemPrice(catalog,name)", inventory)
        self.assertIn("function Inventory.resalePrice", inventory)
        self.assertIn("repairStatus=repairStatus", inventory_actions)
        self.assertIn("repairEquipped=repairEquipped", inventory_actions)
        self.assertIn("LootProgression.audit(Catalog)", inventory_actions)
        self.assertIn("repairStatus=adventure.inventoryActions.repairStatus", view_composition)
        self.assertIn("repairEquipped=adventure.inventoryActions.repairEquipped", input_composition)
        self.assertIn("Inventory.resalePrice", gameplay_input)
        self.assertIn("Inventory.resalePrice", screen_ui)
        self.assertIn("ui.weaponRepair=button", screen_ui)
        self.assertIn("LootProgression.weaponCondition", battle_controller)
        self.assertIn("LootProgression.wearWeapon", battle_controller)
        self.assertIn("Repair it in the train workshop", battle_controller)
        self.assertIn("combat.armorPierce", battle_controller)
        self.assertIn('combat.status=="bleed"', battle_controller)
        self.assertIn('combat.status=="stagger"', battle_controller)
        self.assertIn("function Catalog.weaponReach", catalog)
        self.assertIn("function Catalog.weaponRole", catalog)
        self.assertIn('family="polearm"', catalog)
        self.assertIn('family="axe"', catalog)
        self.assertIn('family="blade"', catalog)
        for asset in ("melee-frontier-v1.png", "melee-blades-v1.png", "melee-polearms-v1.png", "melee-axes-v1.png"):
            self.assertTrue((ROOT / "assets" / "sprites" / "atlases" / asset).is_file(), asset)
        self.assertIn('pcall(require, "game.weapon_attachment_points")', weapon_attachment)
        self.assertIn("function WeaponAttachment.itemSprite", weapon_attachment)
        self.assertIn("generatedHand(file,action,frame,animation)", weapon_attachment)
        self.assertIn("drawHandPatch", weapon_attachment)
        self.assertIn("WeaponAttachment.itemSprite(ui,u.actionItem)", battle_ui)
        self.assertIn("WeaponAttachment.itemSprite(ui,runtime.actionHeldItem)", world_renderer)
        self.assertEqual(54, weapon_attachment_points.count('.png"]={'))
        sludge_assets = (
            "sludge-crawler-mouse-ears-idle-walk.png",
            "sludge-crawler-mouse-ears-attack.png",
            "sludge-crawler-mouse-ears-hit.png",
            "sludge-crawler-mouse-ears-death.png",
        )
        for asset in sludge_assets:
            path = ROOT / "assets" / "sprites" / "Mobs" / "atlases" / asset
            payload = path.read_bytes()
            self.assertEqual(b"\x89PNG\r\n\x1a\n", payload[:8], asset)
            width, height = struct.unpack(">II", payload[16:24])
            self.assertEqual((1254, 1254), (width, height), asset)
            self.assertEqual(0, width % 2, asset)
            self.assertEqual(0, height % 2, asset)
        self.assertIn("loadGeneratedAnimationAtlas", assets)
        self.assertIn("scenery.sludgeAnimations", assets)
        self.assertIn('columns=columns,rows=rows,count=count', assets)
        self.assertIn('local key=columns.."x"..rows..":"..count', stop_sludges)
        self.assertIn("drawStopSludges(sludgeImages())", world_renderer)
        self.assertNotIn("durability-love.math.random", battle_controller)
        self.assertLess(battle_controller.index("LootProgression.wearWeapon"), battle_controller.index("— MISS."))
        self.assertIn('battleGrid = require("game.battle_grid")', systems)
        self.assertIn("Grid.COLS=9", battle_grid)
        self.assertIn("Grid.ROWS=6", battle_grid)
        self.assertIn("function Grid.reachable", battle_grid)
        self.assertIn("function Grid.lineOfSight", battle_grid)
        self.assertIn("function Grid.generateObstacles", battle_grid)
        self.assertIn("function Grid.audit", battle_grid)
        self.assertIn("BattleGrid.generateObstacles", battle_controller)
        self.assertIn("BattleRules.canMove", battle_controller)
        self.assertIn("BattleRules.lineOfSight", battle_controller)
        self.assertNotIn("battleZoom", battle_ui)
        self.assertIn("Camera:setScope(surface())", presentation_runtime)
        self.assertIn("Camera:setZoomAt", presentation_runtime)
        self.assertIn('name="global_camera_input"', smoke_playthrough)
        self.assertIn("function Train.consistLayout", train)
        self.assertIn("if options.mobile then", train)
        self.assertIn("function Train.audit", train)
        self.assertIn('engineTargetWidth=420', train)
        self.assertIn('curve="train-presentation-v2"', train)
        self.assertIn("weaponButtonLabel", battle_ui)
        self.assertIn("(potionIndex-1)*100", battle_ui)
        self.assertNotIn('love.graphics.print(active.name.."  HP "..active.hp.."/"..active.maxHP.."  MOVE "..active.move.."  ARMOR "..active.armor,65,115)', battle_ui)
        self.assertNotIn("targetX-car.x", world_renderer)
        self.assertIn("Train.consistLayout", gameplay_hud)
        self.assertIn("ui.trainCarTabs", gameplay_input)
        self.assertIn("function Maintenance.wearProfile", maintenance)
        self.assertIn("function Maintenance.oilCapacity", maintenance)
        self.assertIn("function Maintenance.audit", maintenance)
        self.assertIn("wearReduction", engine_upgrades)
        self.assertIn('name="responsive_train_presentation"', smoke_playthrough)
        self.assertIn('name="maintenance_route_balance"', smoke_playthrough)
        self.assertIn("scenery.battleObstacles", battle_ui)
        self.assertIn('name="tactical_grid_expansion"', smoke_playthrough)
        for asset in ("battle-obstacles-v1.png", "wasteland-tiles-v4.png", "forest-tiles-v3.png", "town-ruins-tiles-v3.png", "mountain-tiles-v3.png"):
            self.assertTrue((ROOT / "assets" / "sprites" / "battle-maps" / asset).is_file(), asset)
        self.assertIn('local lootBalanceAudit=required(context,"lootBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="loot_equipment_balance"', smoke_playthrough)
        self.assertIn('questProgression = require("game.quest_progression")', systems)
        self.assertIn("questProgression=Modules.questProgression", application_composition)
        self.assertIn('local QuestProgression=required(context,"questProgression","table")', adventure_composition)
        self.assertIn("questProgression=QuestProgression", adventure_composition)
        self.assertIn("function QuestProgression.offerWeights", quest_progression)
        self.assertIn("function QuestProgression.rollOffer", quest_progression)
        self.assertIn("function QuestProgression.rollDelivery", quest_progression)
        self.assertIn("function QuestProgression.deliveryProfile", quest_progression)
        self.assertIn("function QuestProgression.consumeCargo", quest_progression)
        self.assertIn("function QuestProgression.questDistance", quest_progression)
        self.assertIn("function QuestProgression.rewardProfile", quest_progression)
        self.assertIn("function QuestProgression.rollReward", quest_progression)
        self.assertIn("function QuestProgression.storeRewardItem", quest_progression)
        self.assertIn("function QuestProgression.passengerContribution", quest_progression)
        self.assertIn("function QuestProgression.activeObjectives", quest_progression)
        self.assertIn("function QuestProgression.audit", quest_progression)
        self.assertNotIn("cargoStored=true", journey_rules)
        self.assertNotIn("if supply.cargoStored then", journey_rules)
        self.assertIn("QuestProgression.consumeCargo(runtime.saveData,Catalog,supply)", journey_rules)
        self.assertIn("BattleRules.gainExperience", journey_rules)
        self.assertIn("QuestProgression.storeRewardItem", journey_rules)
        self.assertIn("QuestProgression.passengerContribution", journey_rules)
        self.assertIn("questBalanceAudit=function()", journey_rules)
        self.assertIn("questSummary=function()", journey_rules)
        self.assertIn("QuestProgression.rollOffer(location)", stops)
        self.assertIn('finaleProgression = require("game.finale_progression")', systems)
        self.assertIn("function Finale.evaluate", finale_progression)
        self.assertIn("function Finale.choose", finale_progression)
        self.assertIn("function Finale.audit", finale_progression)
        self.assertIn('name="positive_finale_progression"', smoke_playthrough)
        self.assertIn('name="finale_keyboard_choice"', smoke_playthrough)
        self.assertIn("FinaleProgression.evaluate(runtime.saveData,StopHelpProgression,Maintenance)", screen_ui)
        self.assertIn("chooseFinale(control.id)", gameplay_input)
        self.assertIn("function Passengers.preferredCarId", passengers)
        self.assertIn("questSummary=adventure.journeyRules.questSummary", view_composition)
        self.assertIn("local quests=questSummary()", screen_ui)
        self.assertIn('selected.kind=="mailbox" then return "openStorage"', interaction_router)
        self.assertIn("runtime.nearChest or runtime.nearMailbox", gameplay_input)
        self.assertIn('local questBalanceAudit=required(context,"questBalanceAudit","function")', smoke_playthrough)
        self.assertIn('name="quest_passenger_balance"', smoke_playthrough)
        self.assertIn('worldScene = require("game.world_scene")', systems)
        self.assertIn("return {new=new}", world_scene)
        self.assertNotIn("setfenv", world_scene)
        self.assertNotIn("dependency resolver", world_scene)
        self.assertIn("local worldScene=WorldScene.new({", world_session_composition)
        self.assertNotIn("local function setupNPC", app)
        self.assertNotIn("local function updateStopSludges", app)
        self.assertNotIn("function ui.updateChickens", app)
        self.assertIn("resetStopSludges=worldScene.resetStopSludges", world_session_composition)
        self.assertIn("updateWorldScene=world.worldScene.update", startup_composition)
        self.assertIn('audioRuntime = require("game.audio_runtime")', systems)
        self.assertIn("return {new=new}", audio_runtime)
        self.assertNotIn("setfenv", audio_runtime)
        self.assertNotIn("dependency resolver", audio_runtime)
        self.assertIn("audioRuntime=AudioRuntime.new({", platform_composition)
        self.assertNotIn("function ui.playSfx", app)
        self.assertNotIn("function ui.musicCategory", app)
        self.assertNotIn("ui.audio", app)
        self.assertNotIn("ui.audio", gameplay_input)
        self.assertNotIn("ui.audio", gameplay_hud)
        self.assertIn("updateAudio=platform.audioRuntime.update", startup_composition)
        self.assertIn("getAudioStatus=platform.audioRuntime.status", view_composition)
        self.assertIn('inventoryPresenter = require("game.inventory_presenter")', systems)
        self.assertIn("return {new=new}", inventory_presenter)
        self.assertNotIn("setfenv", inventory_presenter)
        self.assertNotIn("dependency resolver", inventory_presenter)
        self.assertIn("inventoryPresenter=InventoryPresenter.new({", view_composition)
        self.assertNotIn("function ui.setInventoryState", app)
        self.assertNotIn("function ui.inventoryContext", app)
        self.assertNotIn("function ui.drawInventory", app)
        self.assertNotIn("ui.inventoryContext", gameplay_input)
        self.assertNotIn("Systems.inventory.handle", gameplay_input)
        self.assertIn("handleInventoryClick=views.inventoryPresenter.handleClick", input_composition)
        self.assertIn("handleInventoryRelease=views.inventoryPresenter.handleRelease", input_composition)
        self.assertIn('eventRuntime = require("game.event_runtime")', systems)
        self.assertIn("return {new=new}", event_runtime)
        self.assertNotIn("setfenv", event_runtime)
        self.assertNotIn("dependency resolver", event_runtime)
        self.assertIn("eventRuntime=EventRuntime.new({", adventure_composition)
        self.assertNotIn("local function resolveEventChoice", app)
        self.assertNotIn("EventUI.hit", gameplay_input)
        self.assertNotIn('required(context,"eventUI"', gameplay_input)
        self.assertNotIn("Events.required", journey_rules)
        self.assertNotIn("Events.random", journey_rules)
        self.assertNotIn("Events.canChoose", screen_ui)
        self.assertIn("chooseEvent=adventure.eventRuntime.choose", input_composition)
        self.assertIn("handleEventClick=adventure.eventRuntime.handleClick", input_composition)
        self.assertIn("canChooseEvent=adventure.eventRuntime.canChoose", view_composition)
        self.assertIn('trainCarRuntime = require("game.train_car_runtime")', systems)
        self.assertIn("return {new=new}", train_car_runtime)
        self.assertNotIn("setfenv", train_car_runtime)
        self.assertNotIn("dependency resolver", train_car_runtime)
        self.assertIn("trainCarRuntime=TrainCarRuntime.new({", platform_composition)
        self.assertNotIn("local function activeTrainCarImage", app)
        self.assertNotIn("local function trainFloorBounds", app)
        self.assertNotIn("local function trainObjectBounds", app)
        self.assertNotIn("local function clampToTrainFloor", app)
        self.assertNotIn("local function beginCarTransition", app)
        self.assertNotIn('required(context,"trainFloorBounds"', gameplay_input)
        self.assertNotIn('required(context,"trainObjectBounds"', gameplay_input)
        self.assertIn("updateCarTransition=platform.trainCarRuntime.updateTransition", startup_composition)
        self.assertIn("beginCarTransition=platform.trainCarRuntime.beginTransition", input_composition)
        self.assertIn('mobileRuntime = require("game.mobile_runtime")', systems)
        self.assertIn("return {new=new}", mobile_runtime)
        self.assertNotIn("setfenv", mobile_runtime)
        self.assertNotIn("dependency resolver", mobile_runtime)
        self.assertIn("mobileRuntime=MobileRuntime.new({", platform_composition)
        self.assertIn("initializeMobile=platform.mobileRuntime.initialize", startup_composition)
        self.assertNotIn("local mobileControls", app)
        self.assertNotIn("MobileControls.new({", app)
        self.assertNotIn('required(context,"mobileControls"', gameplay_update)
        self.assertNotIn("mobileControls:", gameplay_update)
        self.assertNotIn("getMobileControls", gameplay_hud)
        self.assertNotIn("getMobileControls", inventory_presenter)
        self.assertIn("mobileMovement=platform.mobileRuntime.movement", startup_composition)
        self.assertIn("pointerPosition=platform.mobileRuntime.pointerPosition", app)
        self.assertIn("focusMobile=function(...) return mobileRuntime.focus(...) end", platform_composition)
        self.assertIn('presentationRuntime = require("game.presentation_runtime")', systems)
        self.assertIn("return {new=new}", presentation_runtime)
        self.assertNotIn("setfenv", presentation_runtime)
        self.assertNotIn("dependency resolver", presentation_runtime)
        self.assertIn("presentationRuntime=PresentationRuntime.new({", platform_composition)
        self.assertIn("function application.draw() return services.presentationRuntime.draw() end", app)
        self.assertNotIn("local function screenToGame", app)
        self.assertNotIn("Viewport.transform", app)
        self.assertNotIn("Viewport.toGame", app)
        self.assertNotIn("Camera:", app)
        self.assertNotIn("love.graphics.getDimensions", app)
        self.assertIn("Viewport.transform", presentation_runtime)
        self.assertIn("Camera:apply", presentation_runtime)
        self.assertIn("screenToGame=platform.presentationRuntime.screenToGame", app)
        self.assertNotIn('required(context,"camera"', gameplay_input)
        self.assertNotIn('required(context,"viewport"', gameplay_input)
        self.assertNotIn("Camera:", gameplay_input)
        self.assertNotIn("Viewport.", gameplay_input)
        self.assertNotIn('required(context,"camera"', mobile_runtime)
        self.assertNotIn('required(context,"viewport"', mobile_runtime)
        self.assertNotIn("Camera:", mobile_runtime)
        self.assertNotIn("Viewport.", mobile_runtime)
        self.assertIn('startupRuntime = require("game.startup_runtime")', systems)
        self.assertIn('assetStreamer = require("game.asset_streamer")', systems)
        self.assertIn("return {new=new}", startup_runtime)
        self.assertNotIn("setfenv", startup_runtime)
        self.assertNotIn("dependency resolver", startup_runtime)
        self.assertIn("local startupRuntime=StartupRuntime.new({", startup_composition)
        self.assertIn("function application.load() return services.startupRuntime.load() end", app)
        self.assertIn("function application.update(dt) return services.startupRuntime.update(dt) end", app)
        self.assertNotIn("Assets.load", app)
        self.assertNotIn("Settlements.load", app)
        self.assertNotIn("Clouds.new", app)
        self.assertNotIn('require("game.asset_streamer")', app)
        self.assertNotIn("love.graphics.setDefaultFilter", app)
        self.assertNotIn("local cloudLayer", app)
        self.assertNotIn("local characterAnimations", app)
        self.assertIn("characterAnimations=Assets.load(assetTargets)", startup_runtime)
        self.assertIn("initializeMobile()", startup_runtime)
        self.assertIn("gameplayUpdate=GameplayUpdate.new(updateContext)", startup_runtime)
        self.assertIn('persistenceRuntime = require("game.persistence_runtime")', systems)
        self.assertIn("return {new=new}", persistence_runtime)
        self.assertNotIn("setfenv", persistence_runtime)
        self.assertNotIn("dependency resolver", persistence_runtime)
        self.assertIn("persistenceRuntime=PersistenceRuntime.new({", platform_composition)
        self.assertNotIn("local function writeSave", app)
        self.assertIn("writeSave=platform.persistenceRuntime.schedule", app)
        self.assertIn("function application.focus(focused) return services.persistenceRuntime.focus(focused) end", app)
        self.assertIn("function application.quit() services.persistenceRuntime.shutdown() end", app)
        self.assertNotIn("Save.flush()", app)
        self.assertNotIn("Maintenance.release(maintenanceSession)", app)
        self.assertNotIn("Systems.audioRuntime.shutdown()", app)
        self.assertIn("session:scheduleSave(Save)", persistence_runtime)
        self.assertIn("Maintenance.release(maintenanceSession)", persistence_runtime)
        self.assertIn("shutdownAudio()", persistence_runtime)
        self.assertNotIn('required(context,"save"', gameplay_update)
        self.assertNotIn("Save.update", gameplay_update)
        self.assertNotIn('required(context,"save"', gameplay_input)
        self.assertNotIn("Save.read", gameplay_input)
        self.assertNotIn("Save.remove", gameplay_input)
        self.assertNotIn('required(context,"save"', screen_ui)
        self.assertNotIn("Save.read", screen_ui)
        self.assertIn("return {install=install}", smoke_playthrough)
        self.assertNotIn("setfenv", smoke_playthrough)
        self.assertNotIn("setmetatable", smoke_playthrough)
        self.assertNotIn("_G", smoke_playthrough)
        self.assertIn('assert(type(context)=="table","smoke playthrough requires an explicit context")', smoke_playthrough)
        self.assertIn('local game=required(context,"runtime","table")', smoke_playthrough)
        self.assertIn("game.saveData", smoke_playthrough)
        self.assertNotIn('require("game.smoke_playthrough")', app)
        self.assertNotIn("SmokePlaythrough.install({", app)
        self.assertIn("smoke=Modules.smokeComposition.new({", app)
        self.assertIn("function application.installSmoke() return smoke.install() end", app)
        self.assertNotIn("smokeScope", app)
        self.assertNotIn("__index=function", app)
        self.assertNotIn("__newindex=function", app)
        self.assertIn('screenFlow = require("game.screen_flow")', systems)
        self.assertIn("return {new=new}", screen_flow)
        self.assertNotIn("setfenv", screen_flow)
        self.assertNotIn("dependency resolver", screen_flow)
        self.assertIn('services.screenFlow=serviceRegistry.publish("screenFlow",Modules.screenFlow.new({', app)
        self.assertIn("services.screenFlow.install()", app)
        self.assertNotIn("screens:register", app)
        for route in ("intro", "slots", "characters", "battle", "event", "ending", "game"):
            self.assertIn(f'{{"{route}",', screen_flow)
        self.assertIn('local screenFlow=required(context,"screenFlow","table")', smoke_playthrough)
        self.assertIn('contentRegistry = require("game.content_registry")', systems)
        self.assertIn("return {new=new}", content_registry)
        self.assertNotIn("setfenv", content_registry)
        self.assertIn('assert(type(context)=="table","content registry requires an explicit context")', content_registry)
        self.assertIn("local content=Modules.contentRegistry.new({filesystem=Filesystem})", app)
        self.assertNotRegex(app, r"local characters[^\n]*=\s*\{\}")
        self.assertNotIn("local function isFurnitureItem", app)
        self.assertIn("assetTargets=content.assetTargets", startup_composition)
        self.assertIn("legacyAnimationTables=content.legacyAnimationTables", startup_composition)
        self.assertIn("isFurnitureItem=content.isFurnitureItem", world_session_composition)
        self.assertIn('local contentRegistry=required(context,"contentRegistry","table")', smoke_playthrough)
        self.assertIn('name="content_registry_hydrated"', smoke_playthrough)
        self.assertIn('viewComposition = require("game.view_composition")', systems)
        self.assertIn("return {new=new}", view_composition)
        self.assertNotIn("setfenv", view_composition)
        self.assertIn('assert(type(context)=="table","view composition requires an explicit context")', view_composition)
        self.assertNotIn('required(context,"systems"', view_composition)
        self.assertNotIn("Systems.", view_composition)
        self.assertNotIn("local function system", view_composition)
        self.assertIn("local views=Modules.viewComposition.new({", app)
        self.assertIn("platform=platform,adventure=adventure,world=world,startup=startup", app)
        self.assertIn("serviceRegistry.publishAll(views)", app)
        self.assertNotIn("Systems.screenUI=Systems.screenUI.new({", app)
        self.assertNotIn("Systems.inventoryPresenter=Systems.inventoryPresenter.new({", app)
        self.assertNotIn("Systems.worldRenderer=Systems.worldRenderer.new({", app)
        self.assertNotIn("Systems.gameplayHUD=Systems.gameplayHUD.new({", app)
        self.assertIn('local viewComposition=required(context,"viewComposition","table")', smoke_playthrough)
        self.assertIn('name="view_layer_composed"', smoke_playthrough)
        self.assertIn('name="view_dependencies_explicit"', smoke_playthrough)
        self.assertIn('adventureComposition = require("game.adventure_composition")', systems)
        self.assertIn("return {new=new}", adventure_composition)
        self.assertNotIn("setfenv", adventure_composition)
        self.assertIn('assert(type(context)=="table","adventure composition requires an explicit context")', adventure_composition)
        self.assertIn("local adventure=Modules.adventureComposition.new({", app)
        self.assertIn("serviceRegistry.publishAll(adventure)", app)
        self.assertNotIn("Systems.battleRuntime=Systems.battleRuntime.new({", app)
        self.assertNotIn("Systems.inventoryActions=Systems.inventoryActions.new({", app)
        self.assertNotIn("Systems.journeyRules=Systems.journeyRules.new({", app)
        self.assertNotIn("Systems.eventRuntime=Systems.eventRuntime.new({", app)
        self.assertIn('local adventureComposition=required(context,"adventureComposition","table")', smoke_playthrough)
        self.assertIn('name="adventure_services_composed"', smoke_playthrough)
        self.assertIn('platformComposition = require("game.platform_composition")', systems)
        self.assertIn("return {new=new}", platform_composition)
        self.assertNotIn("setfenv", platform_composition)
        self.assertIn('assert(type(context)=="table","platform composition requires an explicit context")', platform_composition)
        self.assertIn("local platform=Modules.platformComposition.new({", app)
        self.assertIn("serviceRegistry.publishAll(platform)", app)
        for direct_constructor in ("persistenceRuntime", "audioRuntime", "trainCarRuntime", "presentationRuntime", "mobileRuntime"):
            self.assertNotIn(f"Systems.{direct_constructor}=Systems.{direct_constructor}.new({{", app)
        self.assertIn('local platformComposition=required(context,"platformComposition","table")', smoke_playthrough)
        self.assertIn('name="platform_services_composed"', smoke_playthrough)
        self.assertIn('inputComposition = require("game.input_composition")', systems)
        self.assertIn("return {new=new}", input_composition)
        self.assertNotIn("setfenv", input_composition)
        self.assertIn('assert(type(context)=="table","input composition requires an explicit context")', input_composition)
        self.assertIn("local input=Modules.inputComposition.new({", app)
        self.assertIn("serviceRegistry.publishAll(input)", app)
        self.assertNotIn("Systems.gameplayInput=Systems.gameplayInput.new({", app)
        for focused_input in ("trainItemAt", "skipIntro", "interactionMouseAction", "interactionKeyAction"):
            self.assertIn(f'local {focused_input}=required(context,"{focused_input}","function")', gameplay_input)
        self.assertIn('local inputComposition=required(context,"inputComposition","table")', smoke_playthrough)
        self.assertIn('name="input_commands_composed"', smoke_playthrough)
        self.assertIn('worldSessionComposition = require("game.world_session_composition")', systems)
        self.assertIn("return {new=new}", world_session_composition)
        self.assertNotIn("setfenv", world_session_composition)
        self.assertIn('assert(type(context)=="table","world/session composition requires an explicit context")', world_session_composition)
        self.assertIn("local world=Modules.worldSessionComposition.new({", app)
        self.assertIn("serviceRegistry.publishAll(world)", app)
        self.assertNotIn("Systems.worldScene=Systems.worldScene.new({", app)
        self.assertNotIn("Systems.sessionBootstrap=Systems.sessionBootstrap.new({", app)
        self.assertIn('local worldSessionComposition=required(context,"worldSessionComposition","table")', smoke_playthrough)
        self.assertIn('name="world_session_composed"', smoke_playthrough)
        self.assertIn('startupComposition = require("game.startup_composition")', systems)
        self.assertIn("return {new=new}", startup_composition)
        self.assertNotIn("setfenv", startup_composition)
        self.assertIn('assert(type(context)=="table","startup composition requires an explicit context")', startup_composition)
        self.assertIn("local startup=Modules.startupComposition.new({", app)
        self.assertIn("serviceRegistry.publishAll(startup)", app)
        self.assertNotIn("Systems.startupRuntime=Systems.startupRuntime.new({", app)
        self.assertIn('local startupComposition=required(context,"startupComposition","table")', smoke_playthrough)
        self.assertIn('name="startup_context_composed"', smoke_playthrough)
        self.assertIn('serviceRegistry = require("game.service_registry")', systems)
        self.assertIn("return {new=new}", service_registry)
        self.assertIn('assert(type(moduleManifest)=="table","service registry requires a module manifest")', service_registry)
        self.assertIn("local Modules = require(\"game.systems\")", app)
        self.assertIn("local serviceRegistry=Modules.serviceRegistry.new(Modules)", app)
        self.assertIn("local services=serviceRegistry.services", app)
        self.assertNotIn("local Systems =", app)
        self.assertNotRegex(app, r"Modules\.[A-Za-z]+\s*=")
        self.assertIn('local serviceRegistry=required(context,"serviceRegistry","table")', smoke_playthrough)
        self.assertIn('name="service_manifest_immutable"', smoke_playthrough)
        self.assertIn('smokeComposition = require("game.smoke_composition")', systems)
        self.assertIn('smokePlaythrough = require("game.smoke_playthrough")', systems)
        self.assertIn("return {new=new}", smoke_composition)
        self.assertIn('assert(type(context)=="table","smoke composition requires an explicit context")', smoke_composition)
        for group in ("state", "domain", "services", "graphs"):
            self.assertIn(f'local {group}=required(context,"context","{group}","table")', smoke_composition)
        self.assertIn("return SmokePlaythrough.install({", smoke_composition)
        self.assertIn("smokeComposition=composition", smoke_composition)
        self.assertNotIn("currentSaveVersion=", app.split("smoke=Modules.smokeComposition.new({", 1)[0])
        self.assertIn('local smokeComposition=required(context,"smokeComposition","table")', smoke_playthrough)
        self.assertIn('name="smoke_context_composed"', smoke_playthrough)
        self.assertIn("return {new=new}", application_composition)
        self.assertIn('assert(type(context)=="table","application composition requires an explicit context")', application_composition)
        self.assertIn('local Engine=required(context,"engine","table")', application_composition)
        self.assertIn("local compositions={platform,world,adventure,startup,views,input,smoke}", application_composition)
        self.assertIn("applicationComposition=application", application_composition)
        self.assertIn('local applicationComposition=required(context,"applicationComposition","table")', smoke_playthrough)
        self.assertIn('name="application_graph_composed"', smoke_playthrough)
        self.assertIn('local balanceAudit=required(context,"balanceAudit","function")', smoke_playthrough)
        self.assertIn('name="progression_balance_curve"', smoke_playthrough)
        self.assertIn('local travelStatus=required(context,"travelStatus","function")', gameplay_input)
        self.assertNotIn('required(context,"travelCost"', gameplay_input)
        self.assertIn('local travelStatus=required(context,"travelStatus","function")', gameplay_hud)
        self.assertIn('or ((travel.affordable and "TRAVEL" or "NEED")', gameplay_hud)

    def test_mobile_package_stages_the_shared_lua_tree(self) -> None:
        builder = (ROOT / "tools" / "build_mobile_package.py").read_text(encoding="utf-8")
        apk_builder = (ROOT / "tools" / "build_android_apk.ps1").read_text(encoding="utf-8")
        self.assertIn('ROOT / "main.lua"', builder)
        self.assertIn('ROOT / "conf.lua"', builder)
        self.assertIn('(ROOT / "game").rglob("*.lua")', builder)
        self.assertFalse(list((ROOT / "mobile").rglob("*.lua")), "mobile must not contain a copied Lua gameplay tree")
        self.assertIn("build_file_index.txt", apk_builder)
        self.assertIn("Invalidating native cache tied to a previous temporary build drive", apk_builder)
        self.assertIn("File]::ReadAllText($gameActivityPath,[System.Text.Encoding]::UTF8)", apk_builder)


if __name__ == "__main__":
    unittest.main()
