from __future__ import annotations

import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]


class LuaArchitectureTests(unittest.TestCase):
    def test_main_is_a_thin_lifecycle_shell(self) -> None:
        source = (ROOT / "main.lua").read_text(encoding="utf-8")
        active_lines = [line for line in source.splitlines() if line.strip() and not line.lstrip().startswith("--")]
        self.assertLessEqual(len(active_lines), 24)
        self.assertIn('require("game.app")', source)
        self.assertEqual(re.findall(r'require\("game\.[^"]+"\)', source), ['require("game.app")'])

        expected_callbacks = {
            "load", "update", "draw", "mousepressed", "mousemoved", "mousereleased",
            "wheelmoved", "keypressed", "keyreleased", "touchpressed", "touchmoved",
            "touchreleased", "focus", "quit",
        }
        forwarded = set(re.findall(r"function love\.([a-z]+)\(", source))
        self.assertEqual(forwarded, expected_callbacks)

    def test_application_boundaries_exist(self) -> None:
        app = (ROOT / "game" / "app.lua").read_text(encoding="utf-8")
        systems = (ROOT / "game" / "systems.lua").read_text(encoding="utf-8")
        schema = (ROOT / "game" / "save_schema.lua").read_text(encoding="utf-8")
        save = (ROOT / "game" / "save.lua").read_text(encoding="utf-8")
        config = (ROOT / "game" / "config.lua").read_text(encoding="utf-8")
        runtime = (ROOT / "game" / "runtime_state.lua").read_text(encoding="utf-8")
        bootstrap = (ROOT / "game" / "session_bootstrap.lua").read_text(encoding="utf-8")
        gameplay_input = (ROOT / "game" / "gameplay_input.lua").read_text(encoding="utf-8")
        gameplay_update = (ROOT / "game" / "gameplay_update.lua").read_text(encoding="utf-8")
        inventory_actions = (ROOT / "game" / "inventory_actions.lua").read_text(encoding="utf-8")
        journey_rules = (ROOT / "game" / "journey_rules.lua").read_text(encoding="utf-8")
        screen_ui = (ROOT / "game" / "screen_ui.lua").read_text(encoding="utf-8")
        world_renderer = (ROOT / "game" / "world_renderer.lua").read_text(encoding="utf-8")
        gameplay_hud = (ROOT / "game" / "gameplay_hud.lua").read_text(encoding="utf-8")
        battle_runtime = (ROOT / "game" / "battle_runtime.lua").read_text(encoding="utf-8")
        world_scene = (ROOT / "game" / "world_scene.lua").read_text(encoding="utf-8")
        audio_runtime = (ROOT / "game" / "audio_runtime.lua").read_text(encoding="utf-8")
        inventory_presenter = (ROOT / "game" / "inventory_presenter.lua").read_text(encoding="utf-8")
        event_runtime = (ROOT / "game" / "event_runtime.lua").read_text(encoding="utf-8")
        train_car_runtime = (ROOT / "game" / "train_car_runtime.lua").read_text(encoding="utf-8")
        mobile_runtime = (ROOT / "game" / "mobile_runtime.lua").read_text(encoding="utf-8")
        presentation_runtime = (ROOT / "game" / "presentation_runtime.lua").read_text(encoding="utf-8")
        startup_runtime = (ROOT / "game" / "startup_runtime.lua").read_text(encoding="utf-8")
        persistence_runtime = (ROOT / "game" / "persistence_runtime.lua").read_text(encoding="utf-8")
        smoke_playthrough = (ROOT / "game" / "smoke_playthrough.lua").read_text(encoding="utf-8")
        screen_flow = (ROOT / "game" / "screen_flow.lua").read_text(encoding="utf-8")
        content_registry = (ROOT / "game" / "content_registry.lua").read_text(encoding="utf-8")
        view_composition = (ROOT / "game" / "view_composition.lua").read_text(encoding="utf-8")
        adventure_composition = (ROOT / "game" / "adventure_composition.lua").read_text(encoding="utf-8")
        platform_composition = (ROOT / "game" / "platform_composition.lua").read_text(encoding="utf-8")
        input_composition = (ROOT / "game" / "input_composition.lua").read_text(encoding="utf-8")
        world_session_composition = (ROOT / "game" / "world_session_composition.lua").read_text(encoding="utf-8")

        for callback in ("load", "update", "draw", "keypressed", "mousepressed", "quit"):
            self.assertIn(f"function App.{callback}", app)
        self.assertTrue(app.rstrip().endswith("return App"))
        self.assertIn('require("game.systems")', app)
        self.assertIn('require("game.save_schema")', app)
        self.assertIn('require("game.config")', app)
        self.assertIn('require("game.runtime_state")', app)
        self.assertNotRegex(app, r"local\s+state\s*=")
        self.assertNotRegex(app, r"local\s+selectedSlot\s*[,=]")
        self.assertNotRegex(app, r"local\s+scene\s*[,=]")
        self.assertIn("CURRENT_VERSION = 25", schema)
        self.assertIn("function SaveSchema.migrate", schema)
        self.assertIn("function SaveSchema.validate", schema)
        self.assertIn("SaveSchema.migrations=migrations", schema)
        self.assertIn("rewriteRequired=steps>0 or not wasCanonical", schema)
        self.assertIn('require("game.save_schema")', save)
        self.assertIn("SaveSchema.migrate(data)", save)
        self.assertIn("SaveSchema.migrate(data)", bootstrap)
        self.assertIn("baseWidth = 960", config)
        self.assertIn("game.gameplay_input", systems)
        self.assertIn("function RuntimeState:syncForSave", runtime)
        self.assertIn("function RuntimeState:isSynchronized", runtime)
        self.assertIn("return {new=new}", bootstrap)
        self.assertNotIn("setfenv", bootstrap)
        self.assertNotIn("dependency resolver", bootstrap)
        self.assertIn("local sessionBootstrap=SessionBootstrap.new({", world_session_composition)
        self.assertIn("return {new=new}", gameplay_input)
        self.assertNotIn("setfenv", gameplay_input)
        self.assertNotIn("dependency resolver", gameplay_input)
        self.assertIn("local gameplayInput=GameplayInput.new({", input_composition)
        self.assertNotIn('required(context,"systems"', gameplay_input)
        self.assertNotIn("Systems.", gameplay_input)
        self.assertIn("return {new=new}", gameplay_update)
        self.assertNotIn("setfenv", gameplay_update)
        self.assertNotIn("dependency resolver", gameplay_update)
        self.assertIn("gameplayUpdate=Systems.gameplayUpdate", app)
        self.assertNotIn("resolveGameplayUpdate", app)
        self.assertIn("return {new=new}", inventory_actions)
        self.assertNotIn("setfenv", inventory_actions)
        self.assertNotIn("dependency resolver", inventory_actions)
        self.assertIn("inventoryActions=InventoryActions.new({", adventure_composition)
        self.assertNotIn("resolveInventoryActions", app)
        self.assertIn("return {new=new}", journey_rules)
        self.assertNotIn("setfenv", journey_rules)
        self.assertNotIn("dependency resolver", journey_rules)
        self.assertIn("journeyRules=JourneyRules.new({", adventure_composition)
        self.assertNotIn("resolveJourneyRules", app)
        self.assertIn("return {new=new}", screen_ui)
        self.assertNotIn("setfenv", screen_ui)
        self.assertNotIn("dependency resolver", screen_ui)
        self.assertIn("screenUI=ScreenUI.new({", view_composition)
        self.assertNotIn("resolveScreenUI", app)
        self.assertIn("return {new=new}", world_renderer)
        self.assertNotIn("setfenv", world_renderer)
        self.assertNotIn("dependency resolver", world_renderer)
        self.assertIn("worldRenderer=WorldRenderer.new({", view_composition)
        self.assertNotIn("resolveWorldRenderer", app)
        self.assertIn("return {new=new}", gameplay_hud)
        self.assertNotIn("setfenv", gameplay_hud)
        self.assertNotIn("dependency resolver", gameplay_hud)
        self.assertIn("gameplayHUD=GameplayHUD.new({", view_composition)
        self.assertNotIn("resolveGameplayHUD", app)
        self.assertIn('battleRuntime = require("game.battle_runtime")', systems)
        self.assertIn("return {new=new}", battle_runtime)
        self.assertNotIn("setfenv", battle_runtime)
        self.assertNotIn("dependency resolver", battle_runtime)
        self.assertIn("battleRuntime=BattleRuntime.new({", adventure_composition)
        self.assertNotIn("local function battleContext", app)
        self.assertNotIn("function ui.battleUIContext", app)
        self.assertIn("useBattleHealingItem=battleRuntime.useHealingItem", adventure_composition)
        self.assertIn('worldScene = require("game.world_scene")', systems)
        self.assertIn("return {new=new}", world_scene)
        self.assertNotIn("setfenv", world_scene)
        self.assertNotIn("dependency resolver", world_scene)
        self.assertIn("local worldScene=WorldScene.new({", world_session_composition)
        self.assertNotIn("local function setupNPC", app)
        self.assertNotIn("local function updateStopSludges", app)
        self.assertNotIn("function ui.updateChickens", app)
        self.assertIn("resetStopSludges=worldScene.resetStopSludges", world_session_composition)
        self.assertIn("updateWorldScene=Systems.worldScene.update", app)
        self.assertIn('audioRuntime = require("game.audio_runtime")', systems)
        self.assertIn("return {new=new}", audio_runtime)
        self.assertNotIn("setfenv", audio_runtime)
        self.assertNotIn("dependency resolver", audio_runtime)
        self.assertIn("audioRuntime=AudioRuntime.new({", platform_composition)
        self.assertNotIn("function ui.playSfx", app)
        self.assertNotIn("function ui.musicCategory", app)
        self.assertNotIn("ui.audio", app)
        self.assertNotIn("ui.audio", gameplay_input)
        self.assertNotIn("ui.audio", gameplay_hud)
        self.assertIn("updateAudio=Systems.audioRuntime.update", app)
        self.assertIn('getAudioStatus=system(Systems,"audioRuntime").status', view_composition)
        self.assertIn('inventoryPresenter = require("game.inventory_presenter")', systems)
        self.assertIn("return {new=new}", inventory_presenter)
        self.assertNotIn("setfenv", inventory_presenter)
        self.assertNotIn("dependency resolver", inventory_presenter)
        self.assertIn("inventoryPresenter=InventoryPresenter.new({", view_composition)
        self.assertNotIn("function ui.setInventoryState", app)
        self.assertNotIn("function ui.inventoryContext", app)
        self.assertNotIn("function ui.drawInventory", app)
        self.assertNotIn("ui.inventoryContext", gameplay_input)
        self.assertNotIn("Systems.inventory.handle", gameplay_input)
        self.assertIn("handleInventoryClick=views.inventoryPresenter.handleClick", input_composition)
        self.assertIn("handleInventoryRelease=views.inventoryPresenter.handleRelease", input_composition)
        self.assertIn('eventRuntime = require("game.event_runtime")', systems)
        self.assertIn("return {new=new}", event_runtime)
        self.assertNotIn("setfenv", event_runtime)
        self.assertNotIn("dependency resolver", event_runtime)
        self.assertIn("eventRuntime=EventRuntime.new({", adventure_composition)
        self.assertNotIn("local function resolveEventChoice", app)
        self.assertNotIn("EventUI.hit", gameplay_input)
        self.assertNotIn('required(context,"eventUI"', gameplay_input)
        self.assertNotIn("Events.required", journey_rules)
        self.assertNotIn("Events.random", journey_rules)
        self.assertNotIn("Events.canChoose", screen_ui)
        self.assertIn("chooseEvent=adventure.eventRuntime.choose", input_composition)
        self.assertIn("handleEventClick=adventure.eventRuntime.handleClick", input_composition)
        self.assertIn('canChooseEvent=system(Systems,"eventRuntime").canChoose', view_composition)
        self.assertIn('trainCarRuntime = require("game.train_car_runtime")', systems)
        self.assertIn("return {new=new}", train_car_runtime)
        self.assertNotIn("setfenv", train_car_runtime)
        self.assertNotIn("dependency resolver", train_car_runtime)
        self.assertIn("trainCarRuntime=TrainCarRuntime.new({", platform_composition)
        self.assertNotIn("local function activeTrainCarImage", app)
        self.assertNotIn("local function trainFloorBounds", app)
        self.assertNotIn("local function trainObjectBounds", app)
        self.assertNotIn("local function clampToTrainFloor", app)
        self.assertNotIn("local function beginCarTransition", app)
        self.assertNotIn('required(context,"trainFloorBounds"', gameplay_input)
        self.assertNotIn('required(context,"trainObjectBounds"', gameplay_input)
        self.assertIn("updateCarTransition=Systems.trainCarRuntime.updateTransition", app)
        self.assertIn("beginCarTransition=platform.trainCarRuntime.beginTransition", input_composition)
        self.assertIn('mobileRuntime = require("game.mobile_runtime")', systems)
        self.assertIn("return {new=new}", mobile_runtime)
        self.assertNotIn("setfenv", mobile_runtime)
        self.assertNotIn("dependency resolver", mobile_runtime)
        self.assertIn("mobileRuntime=MobileRuntime.new({", platform_composition)
        self.assertIn("initializeMobile=Systems.mobileRuntime.initialize", app)
        self.assertNotIn("local mobileControls", app)
        self.assertNotIn("MobileControls.new({", app)
        self.assertNotIn('required(context,"mobileControls"', gameplay_update)
        self.assertNotIn("mobileControls:", gameplay_update)
        self.assertNotIn("getMobileControls", gameplay_hud)
        self.assertNotIn("getMobileControls", inventory_presenter)
        self.assertIn("mobileMovement=Systems.mobileRuntime.movement", app)
        self.assertIn("pointerPosition=Systems.mobileRuntime.pointerPosition", app)
        self.assertIn("focusMobile=function(...) return mobileRuntime.focus(...) end", platform_composition)
        self.assertIn('presentationRuntime = require("game.presentation_runtime")', systems)
        self.assertIn("return {new=new}", presentation_runtime)
        self.assertNotIn("setfenv", presentation_runtime)
        self.assertNotIn("dependency resolver", presentation_runtime)
        self.assertIn("presentationRuntime=PresentationRuntime.new({", platform_composition)
        self.assertIn("function App.draw() return Systems.presentationRuntime.draw() end", app)
        self.assertNotIn("local function screenToGame", app)
        self.assertNotIn("Viewport.transform", app)
        self.assertNotIn("Viewport.toGame", app)
        self.assertNotIn("Camera:", app)
        self.assertNotIn("love.graphics.getDimensions", app)
        self.assertIn("Viewport.transform", presentation_runtime)
        self.assertIn("Camera:apply", presentation_runtime)
        self.assertIn("screenToGame=Systems.presentationRuntime.screenToGame", app)
        self.assertNotIn('required(context,"camera"', gameplay_input)
        self.assertNotIn('required(context,"viewport"', gameplay_input)
        self.assertNotIn("Camera:", gameplay_input)
        self.assertNotIn("Viewport.", gameplay_input)
        self.assertNotIn('required(context,"camera"', mobile_runtime)
        self.assertNotIn('required(context,"viewport"', mobile_runtime)
        self.assertNotIn("Camera:", mobile_runtime)
        self.assertNotIn("Viewport.", mobile_runtime)
        self.assertIn('startupRuntime = require("game.startup_runtime")', systems)
        self.assertIn('assetStreamer = require("game.asset_streamer")', systems)
        self.assertIn("return {new=new}", startup_runtime)
        self.assertNotIn("setfenv", startup_runtime)
        self.assertNotIn("dependency resolver", startup_runtime)
        self.assertIn("Systems.startupRuntime=Systems.startupRuntime.new({", app)
        self.assertIn("function App.load() return Systems.startupRuntime.load() end", app)
        self.assertIn("function App.update(dt) return Systems.startupRuntime.update(dt) end", app)
        self.assertNotIn("Assets.load", app)
        self.assertNotIn("Settlements.load", app)
        self.assertNotIn("Clouds.new", app)
        self.assertNotIn('require("game.asset_streamer")', app)
        self.assertNotIn("love.graphics.setDefaultFilter", app)
        self.assertNotIn("local cloudLayer", app)
        self.assertNotIn("local characterAnimations", app)
        self.assertIn("characterAnimations=Assets.load(assetTargets)", startup_runtime)
        self.assertIn("initializeMobile()", startup_runtime)
        self.assertIn("gameplayUpdate=GameplayUpdate.new(updateContext)", startup_runtime)
        self.assertIn('persistenceRuntime = require("game.persistence_runtime")', systems)
        self.assertIn("return {new=new}", persistence_runtime)
        self.assertNotIn("setfenv", persistence_runtime)
        self.assertNotIn("dependency resolver", persistence_runtime)
        self.assertIn("persistenceRuntime=PersistenceRuntime.new({", platform_composition)
        self.assertNotIn("local function writeSave", app)
        self.assertIn("writeSave=Systems.persistenceRuntime.schedule", app)
        self.assertIn("function App.focus(focused) return Systems.persistenceRuntime.focus(focused) end", app)
        self.assertIn("function App.quit() Systems.persistenceRuntime.shutdown() end", app)
        self.assertNotIn("function App.quit() return", app)
        self.assertNotIn("Save.flush()", app)
        self.assertNotIn("Maintenance.release(maintenanceSession)", app)
        self.assertNotIn("Systems.audioRuntime.shutdown()", app)
        self.assertIn("session:scheduleSave(Save)", persistence_runtime)
        self.assertIn("Maintenance.release(maintenanceSession)", persistence_runtime)
        self.assertIn("shutdownAudio()", persistence_runtime)
        self.assertNotIn('required(context,"save"', gameplay_update)
        self.assertNotIn("Save.update", gameplay_update)
        self.assertNotIn('required(context,"save"', gameplay_input)
        self.assertNotIn("Save.read", gameplay_input)
        self.assertNotIn("Save.remove", gameplay_input)
        self.assertNotIn('required(context,"save"', screen_ui)
        self.assertNotIn("Save.read", screen_ui)
        self.assertIn("return {install=install}", smoke_playthrough)
        self.assertNotIn("setfenv", smoke_playthrough)
        self.assertNotIn("setmetatable", smoke_playthrough)
        self.assertNotIn("_G", smoke_playthrough)
        self.assertIn('assert(type(context)=="table","smoke playthrough requires an explicit context")', smoke_playthrough)
        self.assertIn('local game=required(context,"runtime","table")', smoke_playthrough)
        self.assertIn("game.saveData", smoke_playthrough)
        self.assertIn("SmokePlaythrough.install({", app)
        self.assertNotIn("smokeScope", app)
        self.assertNotIn("__index=function", app)
        self.assertNotIn("__newindex=function", app)
        self.assertIn('screenFlow = require("game.screen_flow")', systems)
        self.assertIn("return {new=new}", screen_flow)
        self.assertNotIn("setfenv", screen_flow)
        self.assertNotIn("dependency resolver", screen_flow)
        self.assertIn("Systems.screenFlow=Systems.screenFlow.new({", app)
        self.assertIn("Systems.screenFlow.install()", app)
        self.assertNotIn("screens:register", app)
        for route in ("intro", "slots", "characters", "battle", "event", "ending", "game"):
            self.assertIn(f'{{"{route}",', screen_flow)
        self.assertIn('local screenFlow=required(context,"screenFlow","table")', smoke_playthrough)
        self.assertIn('contentRegistry = require("game.content_registry")', systems)
        self.assertIn("return {new=new}", content_registry)
        self.assertNotIn("setfenv", content_registry)
        self.assertIn('assert(type(context)=="table","content registry requires an explicit context")', content_registry)
        self.assertIn("local content=Systems.contentRegistry.new({filesystem=love.filesystem})", app)
        self.assertNotRegex(app, r"local characters[^\n]*=\s*\{\}")
        self.assertNotIn("local function isFurnitureItem", app)
        self.assertIn("assetTargets=content.assetTargets", app)
        self.assertIn("legacyAnimationTables=content.legacyAnimationTables", app)
        self.assertIn("isFurnitureItem=content.isFurnitureItem", world_session_composition)
        self.assertIn('local contentRegistry=required(context,"contentRegistry","table")', smoke_playthrough)
        self.assertIn('name="content_registry_hydrated"', smoke_playthrough)
        self.assertIn('viewComposition = require("game.view_composition")', systems)
        self.assertIn("return {new=new}", view_composition)
        self.assertNotIn("setfenv", view_composition)
        self.assertIn('assert(type(context)=="table","view composition requires an explicit context")', view_composition)
        self.assertIn("local views=Systems.viewComposition.new({", app)
        self.assertIn("Systems.screenUI,Systems.inventoryPresenter=views.screenUI,views.inventoryPresenter", app)
        self.assertIn("Systems.worldRenderer,Systems.gameplayHUD=views.worldRenderer,views.gameplayHUD", app)
        self.assertNotIn("Systems.screenUI=Systems.screenUI.new({", app)
        self.assertNotIn("Systems.inventoryPresenter=Systems.inventoryPresenter.new({", app)
        self.assertNotIn("Systems.worldRenderer=Systems.worldRenderer.new({", app)
        self.assertNotIn("Systems.gameplayHUD=Systems.gameplayHUD.new({", app)
        self.assertIn('local viewComposition=required(context,"viewComposition","table")', smoke_playthrough)
        self.assertIn('name="view_layer_composed"', smoke_playthrough)
        self.assertIn('adventureComposition = require("game.adventure_composition")', systems)
        self.assertIn("return {new=new}", adventure_composition)
        self.assertNotIn("setfenv", adventure_composition)
        self.assertIn('assert(type(context)=="table","adventure composition requires an explicit context")', adventure_composition)
        self.assertIn("local adventure=Systems.adventureComposition.new({", app)
        self.assertIn("Systems.battleRuntime,Systems.inventoryActions=adventure.battleRuntime,adventure.inventoryActions", app)
        self.assertIn("Systems.journeyRules,Systems.eventRuntime=adventure.journeyRules,adventure.eventRuntime", app)
        self.assertNotIn("Systems.battleRuntime=Systems.battleRuntime.new({", app)
        self.assertNotIn("Systems.inventoryActions=Systems.inventoryActions.new({", app)
        self.assertNotIn("Systems.journeyRules=Systems.journeyRules.new({", app)
        self.assertNotIn("Systems.eventRuntime=Systems.eventRuntime.new({", app)
        self.assertIn('local adventureComposition=required(context,"adventureComposition","table")', smoke_playthrough)
        self.assertIn('name="adventure_services_composed"', smoke_playthrough)
        self.assertIn('platformComposition = require("game.platform_composition")', systems)
        self.assertIn("return {new=new}", platform_composition)
        self.assertNotIn("setfenv", platform_composition)
        self.assertIn('assert(type(context)=="table","platform composition requires an explicit context")', platform_composition)
        self.assertIn("local platform=Systems.platformComposition.new({", app)
        self.assertIn("Systems.persistenceRuntime,Systems.audioRuntime=platform.persistenceRuntime,platform.audioRuntime", app)
        self.assertIn("Systems.trainCarRuntime,Systems.presentationRuntime=platform.trainCarRuntime,platform.presentationRuntime", app)
        self.assertIn("Systems.mobileRuntime=platform.mobileRuntime", app)
        for direct_constructor in ("persistenceRuntime", "audioRuntime", "trainCarRuntime", "presentationRuntime", "mobileRuntime"):
            self.assertNotIn(f"Systems.{direct_constructor}=Systems.{direct_constructor}.new({{", app)
        self.assertIn('local platformComposition=required(context,"platformComposition","table")', smoke_playthrough)
        self.assertIn('name="platform_services_composed"', smoke_playthrough)
        self.assertIn('inputComposition = require("game.input_composition")', systems)
        self.assertIn("return {new=new}", input_composition)
        self.assertNotIn("setfenv", input_composition)
        self.assertIn('assert(type(context)=="table","input composition requires an explicit context")', input_composition)
        self.assertIn("local input=Systems.inputComposition.new({", app)
        self.assertIn("Systems.gameplayInput=input.gameplayInput", app)
        self.assertNotIn("Systems.gameplayInput=Systems.gameplayInput.new({", app)
        for focused_input in ("trainItemAt", "skipIntro", "interactionMouseAction", "interactionKeyAction"):
            self.assertIn(f'local {focused_input}=required(context,"{focused_input}","function")', gameplay_input)
        self.assertIn('local inputComposition=required(context,"inputComposition","table")', smoke_playthrough)
        self.assertIn('name="input_commands_composed"', smoke_playthrough)
        self.assertIn('worldSessionComposition = require("game.world_session_composition")', systems)
        self.assertIn("return {new=new}", world_session_composition)
        self.assertNotIn("setfenv", world_session_composition)
        self.assertIn('assert(type(context)=="table","world/session composition requires an explicit context")', world_session_composition)
        self.assertIn("local world=Systems.worldSessionComposition.new({", app)
        self.assertIn("Systems.worldScene,Systems.sessionBootstrap=world.worldScene,world.sessionBootstrap", app)
        self.assertNotIn("Systems.worldScene=Systems.worldScene.new({", app)
        self.assertNotIn("Systems.sessionBootstrap=Systems.sessionBootstrap.new({", app)
        self.assertIn('local worldSessionComposition=required(context,"worldSessionComposition","table")', smoke_playthrough)
        self.assertIn('name="world_session_composed"', smoke_playthrough)

    def test_mobile_package_stages_the_shared_lua_tree(self) -> None:
        builder = (ROOT / "tools" / "build_mobile_package.py").read_text(encoding="utf-8")
        self.assertIn('ROOT / "main.lua"', builder)
        self.assertIn('ROOT / "conf.lua"', builder)
        self.assertIn('(ROOT / "game").rglob("*.lua")', builder)
        self.assertFalse(list((ROOT / "mobile").rglob("*.lua")), "mobile must not contain a copied Lua gameplay tree")


if __name__ == "__main__":
    unittest.main()
